config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  devise_for :users

  require "sidekiq/web"

  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :wish_list_items, only: [:create, :destroy] do
    member do
      get :plus_amount
      get :minus_amount
    end
  end

  resources :items, only: [:index, :show]
  get 'compare', to: 'wish_list_items#index', as: 'compare'
  get 'basket', to: 'baskets#show', as: 'basket'

  patch "baskets/:id", to: "baskets#update", as: 'update'
  resources :basket_items, only: :create
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :wish_list_items, dependent: :destroy
  has_many :basket_items, dependent: :destroy
  has_many :baskets, through: :basket_items

  RETAILERS = %w[Tesco Ocado Morrisons]

  validates :name, uniqueness: true, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :generic_name, presence: true
  validates :retailer, inclusion: { in: RETAILERS }
  validates :price, presence: true

  def find_swap
    best_swap = Item.order(emission: :asc).where.not("id = ?", self.id).where("retailer = ? AND sub_category = ? AND emission < ?", self.retailer, self.sub_category, self.emission).first
    # raise
    self.baskets.last.basket_item_ids.each do |id|
      if best_swap
        if BasketItem.find(id).item_id == self.id
          basket_item = BasketItem.find(id)
          # raise
          if Item.find(BasketItem.find(id).item_id).id == best_swap.id
            raise
          elsif best_swap.emission * best_swap.calculate_swap(basket_item) > basket_item.amount * self.emission
            # raise
          # raise
            best_swap = nil
          end
        # elsif Item.find(BasketItem.find(id).item_id).id == best_swap.id
        #   best_swap = nil
        end
      end
    end
    return best_swap
  end

  def calculate_swap(basket_item)
    desired_quantity = basket_item.item.quantity.to_f * basket_item.amount.to_i
    if self.unit == basket_item.item.unit
      required_amount = desired_quantity / self.quantity.to_i
    elsif self.unit == "g" && basket_item.item.unit == "kg"
      required_amount = desired_quantity * 1000 / self.quantity.to_i
    elsif self.unit == "kg" && basket_item.item.unit == "g"
      required_amount = desired_quantity / 1000 / self.quantity.to_i
    elsif self.unit == "each" && basket_item.item.unit != "each"
      if self.category == "fruit"
        required_amount = desired_quantity / 100
      elsif self.category == "vegetable"
        required_amount = desired_quantity / 250
      elsif self.category == ("meat" || "seafood")
        required_amount = desired_quantity / 150
      end
    elsif self.unit != "each" && basket_item.item.unit == "each"
      if self.category == "fruit"
        desired_quantity = desired_quantity * 100
        required_amount = desired_quantity / self.quantity.to_i
      elsif self.category == "vegetable"
        desired_quantity = desired_quantity * 250
        required_amount = desired_quantity / self.quantity.to_i
      elsif self.category == ("meat" || "seafood")
        desired_quantity = desired_quantity * 150
        required_amount = desired_quantity / self.quantity.to_i
      end
    end
    if required_amount < 1
      required_amount = 1
    end
  return required_amount.round
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @wish_list_item = WishListItem.new()
    if params[:query].present?
      @items = Item.where("generic_name ILIKE ?", "%#{params[:query]}%").uniq(&:generic_name)
      @items = category_sorter(@items) if params[:category].present?
    else
      @items = Item.all.uniq(&:generic_name)
      @items = category_sorter(@items) if params[:category].present?
    end
    @wishes = current_user.wish_list_items.order(created_at: :asc)
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def category_sorter(array)
    array.select do |item|
      item.category.downcase == params[:category].downcase
    end
  end
end

app/views/items/_products.html.erb
<div class="row">
  <% items.each do |item| %>
    <%= render 'shared/components/cards', item: item %>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="container grid-container">
  <div class="items">
    <div class="search-bar d-flex">
      <%= form_tag items_path, method: :get, remote: true, class:"full-search-bar" do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search products" %>
        <%= submit_tag "Find a product", class: "btn btn-primary search-btn" %>
      <% end %>
    </div>

    <div class="cat-row">
      <%= link_to items_path(category: ""), remote: true, method: :get, class: "category category-active btn btn-outline-secondary" do %>
        <%= image_tag "filters/all.png", alt: "all", class: 'icon' %>
        All
      <% end %>
      <%= link_to items_path(category: "meat"), remote: true, method: :get, class: "category btn btn-outline-secondary" do %>
        <%= image_tag "filters/meat.png", alt: "meat", class: 'icon' %>
        Meat
      <% end %>
      <%= link_to items_path(category: "seafood"), remote: true, method: :get, class: "category btn btn-outline-secondary" do %>
        <%= image_tag "filters/seafood.png", alt: "seafood", class: 'icon' %>
        Seafood
      <% end %>
      <%= link_to items_path(category: "fruit"), remote: true, method: :get, class: "category btn btn-outline-secondary" do %>
        <%= image_tag "filters/fruits.png", alt: "fruits", class: 'icon' %>
        Fruits
      <% end %>
      <%= link_to items_path(category: "vegetable"), remote: true, method: :get, class: "category btn btn-outline-secondary" do %>
        <%= image_tag "filters/vegetables.png", alt: "vegetables", class: 'icon' %>
        Vegetables
      <% end %>
      <%= link_to items_path(category: "dried goods"), remote: true, method: :get, class: "category btn btn-outline-secondary" do %>
        <%= image_tag "filters/dried-food.png", alt: "Dried goods", class: 'icon' %>
        Dried Goods
      <% end %>
    </div>

    <div id="index-items">
      <%= render 'products', items: @items %>
    </div>
  </div>

  <div class="basket">
    <div class="top-bskt">
      <%= image_tag "filters/basket.png", alt: "basketimage", class: 'icon' %>
      <h2 class="yr-baskt">My basket</h2>
    </div>
    <div class="wish-items" id="wish-items-js">
      <!-- here goes the iteration for the wish list items -->

   <!--    <p id="test">
        <%= @wishes.count %>
      </p> -->
      <% @wishes.each do |wish_list_item| %>
      <div id="item-<%= wish_list_item.id %>">
        <%= render 'shared/components/wish_item', wish_list_item: wish_list_item %>
      </div>
      <% end %>
    </div>
    <div class="con-btn">
      <%= link_to "Compare products", compare_path, class: "btn btn-primary compare-button", id:'compare-btn' %>
    </div>
    </div>
  </div>
</div>

app/views/items/index.js.erb
document.querySelector('#index-items').innerHTML = "<%= j (render 'products', items: @items) %>";