config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/profile', to: 'pages#profile'
  devise_for :users

  require "sidekiq/web"

  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :wish_list_items, only: [:create, :destroy] do
    member do
      get :plus_amount
      get :minus_amount
    end
  end

  resources :items, only: [:index, :show]
  get 'compare', to: 'wish_list_items#index', as: 'compare'
  get 'basket', to: 'baskets#show', as: 'basket'

  patch "baskets/:id", to: "baskets#update", as: 'update'
  resources :basket_items, only: :create
end

app/views/shared/components/_basket_item.html.erb
<div class="product-container">
  <div class="product-img">
    <img src="<%= item.image %>" class="card-img-top" alt="...">
  </div>
  <div class="product-infos">
    <h5 class="card-title"><%= item[:name].capitalize %></h5>
    <h6 class="product_quantity"><%= item. %></h6>
  </div>
</div>

app/views/shared/components/_basketwish.html.erb
<div class="d-flex justify-content-between names-icon">
  <div class="name-quantity">
    <p class="wish-item"><%= @whises.last.item.generic_name.capitalize %></p>
    <p class="wish-item"><%= @whises.last.item.generic_quantity * @whises.last.amount %> <%= @whises.last.item.generic_unit %></p>
  </div>
  <%= link_to plus_amount_wish_list_item_path(@whises.last) do %>
    <p class="wish-item"><i class="fas fa-plus"></i></p>
  <% end %>
  <p class="wish-item"><%= @whises.last.amount %></p>
  <%= link_to minus_amount_wish_list_item_path(@whises.last) do %>
    <p class="wish-item"><i class="fas fa-minus"></i></p>
  <% end %>
  <%= link_to wish_list_item_path(@whises.last), method: :delete do %>
    <p class="wish-item"><i class="fas fa-trash" id="bin"></i></p>
  <% end %>
</div>

app/views/shared/components/_cards-old.html.erb
<div class="col-4 mb-4">
  <div class="card">
    <img src="<%= item.image %>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= item.generic_name.capitalize %></h5>
        <%= form_with model: WishListItem.new, url: wish_list_items_path, remote: true, class: "d-flex" do |form| %>
          <%= form.hidden_field :item_id, value: item.id %>
          <%= form.select :amount, (1..5).map { |i| ["#{item.generic_quantity * i} #{item.generic_unit}", i]}, {}, class: "dropdown-styling" %>
          <button type="submit" class="btn btn-primary add-btn">
            <i class="fas fa-plus-circle"></i>
          </button>
        </form>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/components/_cards.html.erb
<div class="col-4 mb-4">
  <div class="card">
    <img src="<%= item.image %>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= item.generic_name.capitalize %></h5>

      <%#= link_to "Add to order", wish_list_items_path(wish_list_item: { item_id: item, amount: 1 }), remote: true, method: :post, class: "btn" %>
      <%= simple_form_for @wish_list_item, remote: true, method: :post do |f| %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.hidden_field :amount, value: 1 %>
        <%= f.submit "Add to order", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/components/_comparison.html.erb
<div class="comparison-all">
  <div class="comparison-container">
    <div class="comparison-card small-card">
      <%= image_tag "2leaf.png", alt: "twoleafs", class: "leafy" %>
      <%= image_tag "#{@basket[1][0].to_s}.png", alt: @basket[1][0].to_s, class: @basket[1][0].to_s %>
      <div class="comparison-infos">

        <h5 class="comparison-emission"><%= @basket[1][1][:emissions].round %></h5>
        <h6 class="orange-emits">emits</h6>

      </div>
    </div>

    <div class="comparison-card big-card">
      <%= image_tag "3leaf.png", alt: "threeleafs", class: "leafy" %>
      <div class="card-top">
        <%= image_tag "#{@basket[0][0].to_s}.png", alt: @basket[0][0].to_s, class: @basket[0][0].to_s, id: "big-img" %>

        <div class="big-card-emits">
          <h3 class="final-emission"><%= @basket[0][1][:emissions].round %></h3>
          <div>
            <h6 class="orange-emits">emits</h6>
            <p class="price-tag">£<%= '%.2f' % @basket[0][1][:price] %></p>
          </div>
        </div>

      </div>


        <div class="card-bottom">
          <%= link_to basket_path(retailer: @top_basket[0], basket: @top_basket[1]) do %>
            <p class="basket-link">View basket</p>
          <% end %>
        </div>

    </div>
    <div class="comparison-card small-card">
      <%= image_tag "2leaf.png", alt: "twoleafs", class: "leafy" %>
      <%= image_tag "#{@basket[2][0].to_s}.png", alt: @basket[2][0].to_s, class: @basket[2][0].to_s %>
      <div class="comparison-infos">
        <h5 class="comparison-emission"><%= @basket[2][1][:emissions].round%></h5>
        <h6 class="orange-emits">emits</h6>

      </div>
    </div>

    <div class="info-bottom">
      <p>We looked for your items at different retailers and calculated for you the total emissions of your basket. An emit is equivalent to 100g of CO2. As a comparison, flying from London to New York and back generates about 986kg of CO2 per passenger.</p>
    </div>
</div>

app/views/shared/components/_final_basket_items.html.erb
<div class="top-page">
    <div class="header-top-basket">
      <div class="logo-emits">
        <%= image_tag "#{@basket.retailer}.png", alt: "#{@basket}", class: "image-logo-basket" %>
        <div class="number-text">
          <h2 class="final-emission"><%= @basket.emissions.to_i %></h2>
          <div class="emit-price">
            <h6 class="orange-emits">emits</h6>
            <p class="final-price item"> £<%= '%.2f' % @basket.price %> </p>
          </div>
        </div>
      </div>
      <%= link_to 'Download my list', basket_path(@basket, format: :pdf, retailer: @basket.retailer, basket: @basket), class: "btn btn-primary search-btn px-4", target: :_blank %>
    </div>
    <div class="farmer-text">
      <%= image_tag "farmer.png", alt: "farmer" %>
      <% if @total_saving > 0 %>
        <p><strong>Well done!! You have saved <span class="saved-emits"><%= @total_saving %></span> emits!</strong><br>Enjoy your shopping!</p>
      <% else %>
        <p>Your shopping basket is now ready! We found some more <span class="green">eco-friendly or seasonal products</span>, so get swapping and emit less!</p>
      <% end %>
    </div>
  </div>

  <h5 class="basket-headers text-left">My basket</h5>
  <div class="cart-grid">

    <% @basket.items.each do |item| %>
      <div class="product-card pc-out" id="out">
        <%= image_tag "#{item.image}", class: 'product-image', alt: "alttext" %>
        <div class="product-infos">
          <div class="product-infos-left">
            <% if item.name == item.retailer %>
            <% item.name = "#{item.retailer} #{item.generic_name}" %>
            <% else %>
            <% item_name = item_name %>
            <% end %>
            <h5 class="product-name"><%= item.name %></h5>
            <p class="product-quantity"><%= BasketItem.where(item: item).last.amount %> x <%= item.quantity %> <%= item.unit %></p>
          </div>
          <div class="number-text">
            <h2 class="final-emission"><%= item.emission.to_i * BasketItem.where(item_id: item.id).last.amount %></h2>
            <div class="emit-price">
              <h6 class="orange-emits">emits</h6>
              <p class="final-price item"> £<%= '%.2f' % (item.price * BasketItem.where(item_id: item.id).last.amount) %> </p>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex align-items-center justify-content-center">
        <% if item.find_swap %>
          <%= link_to update_path(@basket, swap_out: item, swap_in: item.find_swap, total_saved: @total_saving), method: :patch, remote: true do %>
            <%= image_tag "swap-hd.png", alt: "swap item", class: "swap-button" %>
          <% end %>
        <% end %>
      </div>

      <div class="product-card pc-in" id="in">
        <% if item.find_swap %>
          <%= image_tag "#{item.find_swap.image}", class: 'product-image', alt: "alttext" %>
          <div class="product-infos">
            <div class="product-infos-left">
              <h5 class="product-name"><%= item.find_swap.name %></h5>
              <p class="product-quantity"><%= item.find_swap.calculate_swap(BasketItem.where(item: item).last) %> x <%= item.find_swap.quantity %> <%= item.find_swap.unit %></p>
            </div>
            <div class="number-text">
              <h2 class="final-emission"><%= item.find_swap.emission.to_i * item.find_swap.calculate_swap(BasketItem.where(item: item).last) %></h2>
              <div class="emit-price">
                <h6 class="orange-emits">emits</h6>
                <p class="final-price item"> £<%= '%.2f' % (item.find_swap.price * item.find_swap.calculate_swap(BasketItem.where(item: item).last)) %> </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <!-- <div class="product-card move-out" id="out">
      <img class="product-image" alt="alttext" src="https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=750&amp;q=80">
      <div class="product-infos">
        <div class="product-infos-left">
          <h5 class="product-name">Morrisons Slow Cooked Pork Ribs In Bourbon Bbq Sauce</h5>
          <p class="product-quantity">1 x 544 g</p>
        </div>
        <div class="number-text">
          <h2 class="final-emission">36</h2>
          <div class="emit-price">
            <h6 class="orange-emits">emits</h6>
            <p class="final-price item"> £4.00 </p>
          </div>
        </div>
      </div>
    </div>

    <div class="d-flex align-items-center justify-content-center">
      <a rel="nofollow" data-method="patch" href="/baskets/7?swap_in=49&amp;swap_out=51">
        <img alt="swap item" class="swap-button" src="/assets/swap-hd-2aa5aea31c268ae12ca5deb52e460f6938f2868e1af1c8b1311536c3eaf16a09.png">
      </a>
    </div>

    <div class="product-card move-in" id="in">
      <img class="product-image" alt="alttext" src="https://images.pexels.com/photos/929137/pexels-photo-929137.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260">
      <div class="product-infos">
        <div class="product-infos-left">
          <h5 class="product-name">Morrisons The Best Thick Pork Sausages</h5>
          <p class="product-quantity">1 x 400 g</p>
        </div>
        <div class="number-text">
          <h2 class="final-emission">28</h2>
          <div class="emit-price">
            <h6 class="orange-emits">emits</h6>
            <p class="final-price item"> £2.50 </p>
          </div>
        </div>
      </div>
    </div> -->

    </div>
  </div>

app/views/shared/components/_product_details.html.erb
<div class="product-card">
  <%= image_tag "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjk0Mzg0fQ&auto=format&fit=crop&w=2100&q=80", class: 'product-image', alt: "alttext" %>
  <div class="product-infos">
    <div class="product-infos-left">
      <h5 class="product-name">Blueberry Tesco</h5>
      <p class="product-quantity">300g</p>
    </div>
    <div class="product-infos-right">
      <h5 class="product-emits">35 emits</h5>
      <p class="product-price">£200</p>
    </div>
  </div>
</div>

app/views/shared/components/_wish_item.html.erb
<div class="d-flex justify-content-between names-icon">
  <div class="name-quantity">
    <p class="wish-item"><%= wish_list_item.item.generic_name.capitalize %></p>
  </div>
  <div class="wish-item-actions">
    <%= link_to minus_amount_wish_list_item_path(wish_list_item), remote: true do %>
      <p class="wish-item"><%= image_tag "minus-icon.png", alt: "alttext" %></p>
    <% end %>

    <div class="wish-item-qty">
      <p class="wish-item"><%= wish_list_item.item.generic_quantity * wish_list_item.amount %></p>
      <p class="wish-item-amount"> <%= wish_list_item.item.generic_unit %></p>
    </div>

    <%= link_to plus_amount_wish_list_item_path(wish_list_item), remote: true do %>
      <p class="wish-item"><%= image_tag "plus-icon.png", alt: "alttext" %></p>
    <% end %>
    <%= link_to wish_list_item_path(wish_list_item), method: :delete, remote: true do %>
      <p class="wish-item"><i class="fas fa-trash" id="bin"></i></p>
    <% end %>
  </div>
</div>